id: ICF4306E3
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:59.884481
last_modified: 2023-01-04 11:29:59.884494
source_metadata:
  collections:
  - Böpa Tulku Dongak Tenpe Nyima
  - Works of Tibetan Masters
bases:
  826D:
    title: Biography of Böpa Tulku Dongak Tenpé Nyima
    base_file: 826D.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
